apiVersion: apps/v1
kind: Deployment
metadata:
  name: sdrtgbm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sdrtgbm
  template:
    metadata:
      labels:sdrtgbm
        app: sdrtgbm
    spec:
      containers:
      - image: okteto.dev/sdrtgbm:latest
        name: sdrtgbm
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "7e3b9d41-19ee-4a2b-b16f-bb20ba878ca8"
        - name: Vless_Path
          value: "/xdfgrevl555"
        - name: Vmess_UUID
          value: "7e3b9d41-19ee-4a2b-b16f-bb20ba878ca8"
        - name: Vmess_Path
          value: "/nmhjtrvm666"
        - name: Share_Path
          value: "/v2link"
